version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.3
    container_name: broker
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongo-message:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_message_data:/data/db

  mysql-appointment:
    image: mysql:latest
    ports:
      - 3307:3307
    expose:
      - 3307
    volumes:
      - mysql_appointment_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_TCP_PORT: 3307

  mysql-user:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_user_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123

  service-registry:
    image: chadiai/ede-service-registry
    ports:
      - 8761:8761

  notification-service:
    depends_on:
      - zookeeper
      - broker
      - service-registry
    image: chadiai/ede-notification-service
    ports:
      - 8000:8000
    environment:
      BROKER_BASEURL: broker:9092
      EUREKA_BASEURL: service-registry:8761

  user-service:
    depends_on:
      - mysql-user
      - service-registry
    image: chadiai/ede-user-service
    ports:
      - 8083:8083
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root123
      MYSQL_DB_HOST: mysql-user
      MYSQL_DB_PORT: 3306
      EUREKA_BASEURL: service-registry:8761
      KAFKA_BASEURL: broker:9092

  appointment-service:
    depends_on:
      - mysql-appointment
    image: chadiai/ede-appointment-service
    ports:
      - 8082:8082
    links:
      - mysql-appointment
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root123
      MYSQL_DB_HOST: mysql-appointment
      MYSQL_DB_PORT: 3307
      EUREKA_BASEURL: service-registry:8761

  message-service:
    depends_on:
      - mongo-message
      - service-registry
      - broker
    image: chadiai/ede-message-service
    ports:
      - 8081:8081
    environment:
      BROKER_BASEURL: broker:9092
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-message
      EUREKA_BASEURL: service-registry:8761

  api-gateway:
    depends_on:
      - service-registry
    image: chadiai/ede-api-gateway
    ports:
      - 8080:8080
    environment:
      EUREKA_BASEURL: service-registry:8761

volumes:
  mysql_user_data:
  mysql_appointment_data:
  mongodb_message_data: