server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: signin
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/signin
          filters:
            - SetPath=/api/auth/signin
        - id: user-service-all
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/admin/users
          filters:
            - SetPath=/api/admin/allusers
        - id: appointment-service-all
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/appointments
            - Method=GET
          filters:
            - SetPath=/api/appointment/all
        - id: appointment-service
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/appointment
            - Method=POST
          filters:
            - SetPath=/api/appointment
        - id: message-service-all
          uri: http://${MESSAGE_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/messages
          filters:
            - SetPath=/api/message/all
        - id: message-service-seen
          uri: http://${MESSAGE_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/messages/{isSeen}
          filters:
            - SetPath=/api/message/seen/{isSeen}