server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: appointment-service
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/appointments
            - Method=POST
          filters:
            - SetPath=/api/appointment
        - id: appointment-service-all
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/appointment
            - Method=GET
          filters:
            - SetPath=/api/appointment/all
        - id: notification-service
          uri: http://${NOTIFICATION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/notifications
          filters:
            - SetPath=/api/notification