spring:
  application:
    name: USER-SERVICE


eureka:
  client:
    service-url:
      defaultZone : http://${EUREKA_BASEURL:localhost:8761}/eureka/

server:
  port: 8083

jwt:
  secret: ${SECRET:DD89FFA52F582D22BD5A6FCEAC8FD6EDF8852B17FA2FC139BC8CA4B7AF}