spring:
 cloud:
   gateway:
     routes:
       - id: message-service
         uri: lb://MESSAGE-SERVICE
         predicates:
           - Path=/messages/**
         filters:
           - AuthenticationFilter

       - id: appointment-service
         uri: lb://APPOINTMENT-SERVICE
         predicates:
           - Path=/appointment/**
         filters:
           - AuthenticationFilter

       - id: user-service
         uri: lb://USER-SERVICE
         predicates:
           - Path=/auth/**
         filters:
           - AuthenticationFilter

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://${EUREKA_BASEURL:localhost:8761}/eureka/

jwt:
  secret: ${SECRET:DD89FFA52F582D22BD5A6FCEAC8FD6EDF8852B17FA2FC139BC8CA4B7AF}